/** Canyon Outdoor About page: establish a local, climate-aware studio perspective without overwhelming the visitor. */
import { MapView } from "@/components/Map";
import { BrandLockup, PageIntro, SiteFooter, SiteHeader } from "@/components/SiteChrome";
import { QuickContactForm } from "@/components/QuickContactForm";

export default function About() {
  return <><SiteHeader /><main className="bg-[#f4f2eb] pt-32 text-[#1d2b20] md:pt-40"><section className="pb-24 md:pb-32"><div className="container"><PageIntro eyebrow="Rooted nearby" title={<>BUILT FOR SOUTHERN<br />CALIFORNIA LIVING.</>} copy="Canyon Outdoor is rooted in Orange County and shaped by the region's light, climate, material palette, and easy connection between indoors and out." />
    <div className="mt-14 grid overflow-hidden rounded-[1.5rem] border border-[#1d2b20]/10 lg:grid-cols-[1.2fr_0.8fr]"><div className="relative min-h-[400px]"><MapView initialCenter={{ lat: 33.6704, lng: -117.822 } as google.maps.LatLngLiteral} initialZoom={10} className="map-canvas h-full min-h-[400px] w-full" /><div className="absolute left-5 top-5 rounded-full bg-[#f8f7f1]/90 px-4 py-2 text-sm font-semibold text-[#173221] shadow-sm backdrop-blur">Orange County, CA</div></div><div className="flex flex-col justify-between bg-[#e0e7d9] p-7 md:p-10"><div><p className="text-2xl font-semibold">Close to the land.</p><p className="mt-4 max-w-sm text-sm leading-7 text-[#1d2b20]/65">For a location not listed, an inquiry is the best way to see if the project is a fit.</p></div><div className="mt-12 flex flex-wrap gap-2">{["Huntington Beach", "Newport Beach", "Costa Mesa", "Irvine", "Fountain Valley", "Anaheim"].map(areaName => <span key={areaName} className="rounded-full border border-[#1d2b20]/15 bg-white/40 px-3 py-2 text-xs text-[#1d2b20]/75">{areaName}</span>)}</div></div></div></div></section>
    <section className="bg-[#e0e7d9] py-24 md:py-32"><div className="container grid gap-12 lg:grid-cols-[0.42fr_0.58fr]"><div><BrandLockup /><p className="mt-7 max-w-xs text-base leading-7 text-[#1d2b20]/66">A growing studio with a more complete view of what outdoor spaces can become.</p></div><div><h2 className="display max-w-4xl text-5xl font-bold leading-[0.88] md:text-7xl">WE SEE MORE<br />THAN A YARD.</h2><p className="mt-8 max-w-2xl text-lg leading-8 text-[#1d2b20]/70">Canyon Outdoor approaches exterior space as an extension of the property and the people who use it. We consider sun paths, shade, planting depth, water, material character, and the rituals that bring a landscape to life.</p></div></div></section>
  </main><QuickContactForm /><SiteFooter /></>;
}
