/** Canyon Outdoor Contact page: a focused, multi-step project brief with clear language and a calm visual cadence. */
import { FormEvent, useState } from "react";
import { ArrowRight, Check, ChevronLeft, ChevronRight, Sparkles } from "lucide-react";
import { BrandLockup, PageIntro, SiteFooter, SiteHeader } from "@/components/SiteChrome";

const inquiryTypes = ["Landscape design", "Outdoor living", "Hardscape concept", "Backyard transformation", "Property visualization", "Not sure yet"];

export default function Contact() {
  const [step, setStep] = useState(0); const [inquiryType, setInquiryType] = useState<string[]>([]); const [propertyType, setPropertyType] = useState(""); const [area, setArea] = useState(""); const [details, setDetails] = useState(""); const [fileName, setFileName] = useState(""); const [submitted, setSubmitted] = useState(false);
  const toggleInquiry = (item: string) => setInquiryType(current => current.includes(item) ? current.filter(value => value !== item) : [...current, item]);
  const submitInquiry = (event: FormEvent) => { event.preventDefault(); setSubmitted(true); };
  return <><SiteHeader /><main className="soft-mesh min-h-screen pt-32 text-[#1d2b20] md:pt-40"><section className="pb-24 md:pb-32"><div className="container"><PageIntro eyebrow="Project inquiry" title={<>LET'S CREATE YOUR<br />OUTDOOR SPACE.</>} copy="Share what you are imagining. This short guided inquiry gives us a helpful place to start." />
    <div className="mt-14 overflow-hidden rounded-[1.5rem] border border-[#1d2b20]/10 bg-[#f9f8f3] shadow-[0_25px_70px_rgba(35,52,38,0.12)]">{submitted ? <div className="grid min-h-[460px] place-items-center p-8 text-center"><div className="max-w-lg"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#173221] text-white"><Check size={25} /></div><h2 className="display mt-7 text-5xl font-semibold leading-[0.92]">WE'VE GOT IT.</h2><p className="mx-auto mt-5 max-w-md text-base leading-7 text-[#1d2b20]/65">Thanks for reaching out to Canyon Outdoor. We’ll review your project information and get back to you.</p><button onClick={() => { setSubmitted(false); setStep(0); }} className="mt-8 rounded-full border border-[#1d2b20]/20 px-5 py-3 text-sm font-semibold">Start another inquiry</button></div></div> : <form onSubmit={submitInquiry} className="grid lg:grid-cols-[0.3fr_0.7fr]"><aside className="bg-[#173221] p-7 text-white md:p-9"><BrandLockup light compact /><p className="mt-10 text-lg leading-8 text-white/72">A few details now make a more useful first conversation later.</p><div className="mt-12 flex gap-2">{[0, 1, 2, 3, 4, 5].map(item => <button type="button" key={item} onClick={() => setStep(item)} className={`h-2.5 rounded-full transition-all ${step === item ? "w-8 bg-[#b9d3b5]" : "w-2.5 bg-white/25"}`} aria-label={`Go to form step ${item + 1}`} />)}</div></aside><div className="min-h-[480px] p-7 md:p-10 lg:p-14">
      {step === 0 && <div><h2 className="display text-4xl font-semibold leading-[0.95] md:text-5xl">WHAT ARE YOU<br />IMAGINING?</h2><p className="mt-4 text-sm leading-6 text-[#1d2b20]/60">Choose anything that feels relevant right now.</p><div className="mt-8 grid gap-2 sm:grid-cols-2">{inquiryTypes.map(item => <button type="button" key={item} onClick={() => toggleInquiry(item)} className={`flex items-center justify-between rounded-xl border p-4 text-left text-sm font-semibold transition-colors ${inquiryType.includes(item) ? "border-[#35563d] bg-[#e0e7d9]" : "border-[#1d2b20]/15 hover:border-[#35563d]"}`}><span>{item}</span>{inquiryType.includes(item) && <Check size={17} className="text-[#35563d]" />}</button>)}</div></div>}
      {step === 1 && <div><h2 className="display text-4xl font-semibold leading-[0.95] md:text-5xl">WHAT KIND OF<br />PROPERTY IS IT?</h2><div className="mt-8 grid gap-3 sm:grid-cols-3">{["Residential", "Commercial", "Other"].map(item => <button type="button" key={item} onClick={() => setPropertyType(item)} className={`min-h-32 rounded-2xl border p-5 text-left text-lg font-semibold transition-colors ${propertyType === item ? "border-[#35563d] bg-[#e0e7d9]" : "border-[#1d2b20]/15 hover:border-[#35563d]"}`}>{item}</button>)}</div></div>}
      {step === 2 && <div><h2 className="display text-4xl font-semibold leading-[0.95] md:text-5xl">WHERE IS THE<br />PROJECT LOCATED?</h2><p className="mt-4 text-sm leading-6 text-[#1d2b20]/60">A city or general neighborhood is enough for a first look.</p><input value={area} onChange={event => setArea(event.target.value)} placeholder="e.g. Costa Mesa, CA" className="mt-10 w-full border-b border-[#1d2b20]/25 bg-transparent py-4 text-2xl font-semibold outline-none placeholder:text-[#1d2b20]/28 focus:border-[#35563d]" /></div>}
      {step === 3 && <div><h2 className="display text-4xl font-semibold leading-[0.95] md:text-5xl">WHAT SHOULD<br />FEEL DIFFERENT?</h2><textarea value={details} onChange={event => setDetails(event.target.value)} placeholder="Tell us about the site, what is not working now, and the experience you are hoping to create." className="mt-8 min-h-52 w-full resize-none rounded-2xl border border-[#1d2b20]/15 bg-transparent p-5 text-sm leading-7 outline-none placeholder:text-[#1d2b20]/35 focus:border-[#35563d]" /></div>}
      {step === 4 && <div><h2 className="display text-4xl font-semibold leading-[0.95] md:text-5xl">SHOW US WHAT<br />INSPIRES YOU.</h2><label className="mt-8 flex min-h-48 flex-col items-center justify-center rounded-2xl border border-dashed border-[#1d2b20]/30 bg-[#e0e7d9]/55 p-6 text-center transition-colors hover:bg-[#e0e7d9]"><Sparkles size={22} className="mb-4 text-[#35563d]" /><span className="text-sm font-semibold">{fileName || "Choose an image or drop it here"}</span><span className="mt-2 text-xs text-[#1d2b20]/55">A reference photo or simple site image is welcome.</span><input type="file" accept="image/*" className="sr-only" onChange={event => setFileName(event.target.files?.[0]?.name || "")} /></label></div>}
      {step === 5 && <div><h2 className="display text-4xl font-semibold leading-[0.95] md:text-5xl">HOW CAN WE<br />REACH YOU?</h2><div className="mt-8 grid gap-4 sm:grid-cols-2"><input required placeholder="Name" className="border-b border-[#1d2b20]/25 bg-transparent py-4 text-sm outline-none placeholder:text-[#1d2b20]/40 focus:border-[#35563d]" /><input required type="email" placeholder="Email address" className="border-b border-[#1d2b20]/25 bg-transparent py-4 text-sm outline-none placeholder:text-[#1d2b20]/40 focus:border-[#35563d]" /><input placeholder="Phone (optional)" className="border-b border-[#1d2b20]/25 bg-transparent py-4 text-sm outline-none placeholder:text-[#1d2b20]/40 focus:border-[#35563d]" /><input placeholder="Best time to connect (optional)" className="border-b border-[#1d2b20]/25 bg-transparent py-4 text-sm outline-none placeholder:text-[#1d2b20]/40 focus:border-[#35563d]" /></div></div>}
      <div className="mt-12 flex items-center justify-between border-t border-[#1d2b20]/12 pt-5"><button type="button" onClick={() => setStep(current => Math.max(0, current - 1))} disabled={step === 0} className="flex items-center gap-1 text-sm font-semibold disabled:opacity-25"><ChevronLeft size={16} />Back</button>{step < 5 ? <button type="button" onClick={() => setStep(current => Math.min(5, current + 1))} className="flex items-center gap-2 rounded-full bg-[#173221] px-5 py-3 text-sm font-semibold text-white">Continue <ChevronRight size={16} /></button> : <button type="submit" className="flex items-center gap-2 rounded-full bg-[#35563d] px-5 py-3 text-sm font-semibold text-white">Send inquiry <ArrowRight size={16} /></button>}</div></div></form>}</div></div></section></main><SiteFooter /></>;
}
