/** Canyon Outdoor environmental direction: clean modern typography, lush buildable concepts, calm surface layers, and human-centered interactions. */
import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowRight, Check, ChevronLeft, ChevronRight, Droplets, Flame, Leaf, MapPin, Menu, MoveHorizontal, Sparkles, Sun, X } from "lucide-react";
import { MapView } from "@/components/Map";

const ASSETS = {
  hero: "/manus-storage/canyon-lush-hero_c3aabbb0.jpg",
  before: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1700&q=85",
  concept: "/manus-storage/canyon-before-concept_1a3746e8.png",
  water: "/manus-storage/canyon-water-living_b5d75082.jpg",
  detail: "/manus-storage/canyon-green-detail_ce8147b0.jpg",
  patio: "/manus-storage/canyon-patio_196b7aa9.jpg",
  symbol: "/manus-storage/canyon-symbol_92480f48.png",
};

const navLinks = ["Work", "Services", "Process", "About", "Contact"];
const properties = ["Backyard", "Front yard", "Whole property"];
const styles = ["Modern", "California", "Natural"];
const features = ["Layered planting", "Water feature", "Fire feature", "Patio", "Outdoor kitchen", "Lighting"];
const inquiryTypes = ["Landscape design", "Outdoor living", "Hardscape concept", "Backyard transformation", "Property visualization", "Not sure yet"];

function BrandLockup({ light = false, compact = false }: { light?: boolean; compact?: boolean }) {
  return <div className={`brand-lockup ${light ? "text-[#f7f6f0]" : "text-[#173221]"}`}>
    <img src={ASSETS.symbol} alt="" className={compact ? "h-8 w-8 object-contain" : "h-10 w-10 object-contain"} />
    <span className="brand-lockup__type text-[0.66rem] font-bold tracking-[0.16em]"><span>CANYON</span><span className="brand-lockup__horizon">OUTDOOR</span></span>
  </div>;
}

function ArrowLink({ label, light = false }: { label: string; light?: boolean }) {
  return <span className={`inline-flex items-center gap-2 text-sm font-semibold ${light ? "text-white" : "text-[#173221]"}`}>{label}<span className={`grid h-7 w-7 place-items-center rounded-full ${light ? "border border-white/30" : "bg-[#173221] text-white"}`}><ArrowRight size={14} /></span></span>;
}

function SectionHeading({ eyebrow, title, copy, light = false }: { eyebrow: string; title: React.ReactNode; copy?: string; light?: boolean }) {
  return <div className={`grid gap-7 lg:grid-cols-[1.1fr_0.55fr] lg:items-end ${light ? "text-[#f8f7f1]" : "text-[#1d2b20]"}`}>
    <div><div className="mb-4 flex items-center gap-2"><img src={ASSETS.symbol} alt="" className="h-6 w-6 object-contain" /><p className={`eyebrow ${light ? "text-[#b9d3b5]" : "text-[#52705b]"}`}>{eyebrow}</p></div><h2 className="display max-w-3xl text-5xl font-bold leading-[0.9] md:text-7xl">{title}</h2></div>
    {copy && <p className={`max-w-md text-base leading-7 ${light ? "text-white/70" : "text-[#1d2b20]/67"}`}>{copy}</p>}
  </div>;
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [comparison, setComparison] = useState(50);
  const [property, setProperty] = useState("Backyard");
  const [style, setStyle] = useState("California");
  const [selectedFeatures, setSelectedFeatures] = useState<string[]>(["Layered planting", "Water feature", "Fire feature"]);
  const [step, setStep] = useState(0);
  const [inquiryType, setInquiryType] = useState<string[]>([]);
  const [propertyType, setPropertyType] = useState("");
  const [area, setArea] = useState("");
  const [details, setDetails] = useState("");
  const [fileName, setFileName] = useState("");
  const [submitted, setSubmitted] = useState(false);

  useEffect(() => {
    document.body.style.overflow = menuOpen ? "hidden" : "";
    return () => { document.body.style.overflow = ""; };
  }, [menuOpen]);

  const selectedSummary = useMemo(() => selectedFeatures.length ? selectedFeatures.join(" · ") : "Choose the elements that feel right for you", [selectedFeatures]);
  const toggleFeature = (feature: string) => setSelectedFeatures(current => current.includes(feature) ? current.filter(item => item !== feature) : [...current, feature]);
  const toggleInquiry = (item: string) => setInquiryType(current => current.includes(item) ? current.filter(value => value !== item) : [...current, item]);
  const nextStep = () => setStep(current => Math.min(5, current + 1));
  const prevStep = () => setStep(current => Math.max(0, current - 1));
  const submitInquiry = (event: FormEvent) => { event.preventDefault(); setSubmitted(true); };

  return <main className="bg-[#f4f2eb] text-[#1d2b20] selection:bg-[#35563d] selection:text-white">
    <header className="fixed inset-x-0 top-0 z-50 px-4 py-4 sm:px-6">
      <div className="mx-auto flex max-w-[980px] items-center justify-between rounded-full border border-white/35 bg-[#f8f7f1]/85 px-3 py-2 shadow-[0_14px_38px_rgba(21,42,26,0.18)] backdrop-blur-xl">
        <a href="#top" className="shrink-0" aria-label="Canyon Outdoor home"><BrandLockup compact /></a>
        <nav className="hidden items-center gap-5 lg:flex" aria-label="Primary navigation">{navLinks.map(link => <a key={link} href={`#${link.toLowerCase()}`} className="text-xs font-semibold text-[#1d2b20]/65 transition-colors hover:text-[#1d2b20]">{link}</a>)}</nav>
        <button onClick={() => setMenuOpen(true)} className="flex items-center gap-2 rounded-full bg-[#1d2b20] px-4 py-2 text-xs font-bold text-white transition-transform active:scale-95" aria-label="Open menu"><span>Menu</span><Menu size={15} /></button>
      </div>
    </header>

    <div className={`fixed inset-0 z-[60] transition-opacity duration-300 ${menuOpen ? "pointer-events-auto opacity-100" : "pointer-events-none opacity-0"}`} aria-hidden={!menuOpen}>
      <button className="absolute inset-0 bg-[#102015]/45 backdrop-blur-sm" onClick={() => setMenuOpen(false)} aria-label="Close menu overlay" />
      <div className={`menu-surface absolute left-1/2 top-4 w-[calc(100%-2rem)] max-w-[930px] -translate-x-1/2 overflow-hidden rounded-[1.7rem] border border-white/10 text-white transition-all duration-500 ${menuOpen ? "translate-y-0 opacity-100" : "-translate-y-6 opacity-0"}`}>
        <div className="flex items-center justify-between border-b border-white/12 px-5 py-4 sm:px-7"><BrandLockup light compact /><button onClick={() => setMenuOpen(false)} className="grid h-10 w-10 place-items-center rounded-full bg-white text-[#173221]" aria-label="Close menu"><X size={18} /></button></div>
        <div className="relative grid gap-10 overflow-hidden px-6 py-10 sm:grid-cols-[1fr_0.85fr] sm:px-10 sm:py-12"><img src={ASSETS.detail} alt="" className="absolute inset-y-0 right-0 h-full w-1/2 object-cover opacity-20" /><nav className="relative grid content-start" aria-label="Expanded navigation"><p className="eyebrow mb-6 text-[#b9d3b5]">Explore Canyon Outdoor</p>{navLinks.map(link => <a onClick={() => setMenuOpen(false)} key={link} href={`#${link.toLowerCase()}`} className="border-t border-white/15 py-3.5 text-3xl font-semibold leading-none transition-colors hover:text-[#b9d3b5] sm:text-4xl">{link}</a>)}</nav>
          <div className="relative flex flex-col justify-end"><p className="max-w-sm text-lg leading-8 text-white/75">Modern outdoor environments with deeper planting, water, fire, and space to slow down.</p><a onClick={() => setMenuOpen(false)} href="#contact" className="mt-8 inline-block"><ArrowLink label="Tell us about your space" light /></a><div className="mt-12 flex items-center gap-2 text-sm text-white/55"><MapPin size={15} className="text-[#b9d3b5]" />Orange County, California</div></div></div>
      </div>
    </div>

    <section id="top" className="soft-mesh relative isolate min-h-[790px] overflow-hidden pt-28 md:min-h-[840px] md:pt-36">
      <img src={ASSETS.hero} alt="Lush contemporary Southern California outdoor space with planting, water, and fire" className="absolute inset-x-0 bottom-0 h-[43%] w-full object-cover md:left-[36%] md:h-full md:w-[64%]" />
      <div className="absolute inset-x-0 bottom-0 h-[68%] bg-gradient-to-t from-[#14301d]/80 via-[#173221]/10 to-transparent md:inset-y-0 md:left-[25%] md:h-auto md:bg-gradient-to-r md:from-[#f4f2eb] md:via-[#f4f2eb]/72 md:to-transparent" />
      <img src={ASSETS.symbol} alt="" className="pointer-events-none absolute right-[9%] top-[22%] hidden h-40 w-40 opacity-25 md:block" />
      <div className="container relative flex min-h-[790px] flex-col justify-between pb-10 md:min-h-[840px] md:pb-14"><div className="pt-16 md:pt-20"><div className="plant-glass inline-flex items-center gap-2 rounded-full px-3 py-2 text-xs font-semibold text-[#31563a]"><Leaf size={14} /> Southern California landscape design</div>
        <h1 className="display mt-7 max-w-4xl text-[clamp(4.2rem,9.7vw,8.8rem)] font-bold leading-[0.82] text-[#1b2e20]">OUTDOORS,<br /><span className="text-[#52705b]">REIMAGINED.</span></h1><p className="mt-7 max-w-md text-base leading-7 text-[#1b2e20]/72 md:text-lg">Landscape concepts shaped by Southern California light, layered planting, and the way a property moves from shade to firelight.</p><div className="mt-8"><a href="#work" className="inline-block rounded-full bg-[#1d2b20] px-5 py-3.5"><ArrowLink label="Explore our work" light /></a></div></div>
        <div className="flex items-center gap-3 text-xs font-semibold text-white md:text-[#1b2e20]/60"><span className="grid h-8 w-8 place-items-center rounded-full border border-current/30"><ArrowDown size={14} /></span>Scroll to explore</div></div>
    </section>

    <section id="work" className="py-24 md:py-32"><div className="container"><SectionHeading eyebrow="Visualize before you build" title={<>A CLEARER WAY<br />TO SEE YOUR SPACE.</>} copy="A thoughtful concept keeps the house, light, circulation, and character of the property in view—then makes the landscape opportunity tangible." />
      <div className="mt-14 grid gap-7 lg:grid-cols-[1fr_300px]"><div className="relative aspect-[1.25/1] overflow-hidden rounded-[1.5rem] bg-[#d8ddd0] shadow-[0_18px_45px_rgba(36,59,40,0.11)] md:aspect-[1.7/1]"><img src={ASSETS.before} alt="Existing property" className="absolute inset-0 h-full w-full object-cover brightness-90" /><div className="absolute inset-y-0 left-0 overflow-hidden" style={{ width: `${comparison}%` }}><img src={ASSETS.concept} alt="Canyon Outdoor redesign concept for the same home" className="h-full max-w-none w-[calc(100vw-2.5rem)] object-cover md:w-[min(100%,1000px)]" /></div><div className="absolute inset-y-0 z-10 w-px bg-white shadow-[0_0_0_1px_rgba(0,0,0,.16)]" style={{ left: `${comparison}%` }}><button aria-label="Drag before and after comparison" className="absolute left-1/2 top-1/2 grid h-12 w-12 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-white text-[#1d2b20] shadow-lg" onPointerDown={event => { const parent = event.currentTarget.parentElement?.parentElement; if (!parent) return; const move = (moveEvent: PointerEvent) => { const rect = parent.getBoundingClientRect(); setComparison(Math.max(3, Math.min(97, ((moveEvent.clientX - rect.left) / rect.width) * 100))); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", () => window.removeEventListener("pointermove", move), { once: true }); }}><MoveHorizontal size={18} /></button></div><span className="absolute left-5 top-5 rounded-full bg-[#173221]/80 px-3 py-1.5 text-xs font-semibold text-white backdrop-blur">Canyon concept</span><span className="absolute right-5 top-5 rounded-full bg-white/85 px-3 py-1.5 text-xs font-semibold text-[#173221] backdrop-blur">Existing property</span></div>
        <aside className="rounded-[1.5rem] bg-[#173221] p-7 text-white md:p-8"><Leaf className="text-[#b9d3b5]" size={22} /><h3 className="display mt-8 text-3xl font-semibold leading-[0.94]">KEEP THE HOME.<br />GROW THE OUTDOORS.</h3><p className="mt-5 text-sm leading-7 text-white/70">The redesigned concept uses the same architecture and vantage point, then brings in layered planting, a water element, clear paths, and firelight.</p><div className="mt-8 flex flex-wrap gap-2"><span className="rounded-full bg-white/10 px-3 py-2 text-xs">Lush planting</span><span className="rounded-full bg-white/10 px-3 py-2 text-xs">Water</span><span className="rounded-full bg-white/10 px-3 py-2 text-xs">Fire</span></div></aside></div></div></section>

    <section id="services" className="relative overflow-hidden bg-[#e0e7d9] py-24 md:py-32"><div className="soft-mesh absolute inset-0 opacity-65" /><div className="container relative"><SectionHeading eyebrow="Designed for real life" title={<>MORE GREEN.<br />MORE OUTSIDE.</>} copy="We balance planting, shade, water, and durable materials around the daily rituals that make an outdoor space worth using." />
      <div className="mt-14 grid gap-4 md:grid-cols-3"><article className="plant-glass overflow-hidden rounded-[1.5rem] p-6"><Leaf className="text-[#52705b]" /><h3 className="display mt-10 text-3xl font-semibold">Landscape design</h3><p className="mt-4 text-sm leading-6 text-[#1d2b20]/65">Layered planting, textures, shade, and materials shaped around the site.</p><img src={ASSETS.detail} alt="Lush modern planting detail" className="mt-7 aspect-[1.35/1] w-full rounded-2xl object-cover" /></article><article className="overflow-hidden rounded-[1.5rem] bg-[#173221] p-6 text-white"><Droplets className="text-[#b9d3b5]" /><h3 className="display mt-10 text-3xl font-semibold">Outdoor living</h3><p className="mt-4 text-sm leading-6 text-white/70">Calm water, gathering spaces, fire features, and the simple joy of staying outside longer.</p><img src={ASSETS.water} alt="Contemporary courtyard with water and fire feature" className="mt-7 aspect-[1.35/1] w-full rounded-2xl object-cover" /></article><article className="plant-glass overflow-hidden rounded-[1.5rem] p-6"><Sparkles className="text-[#52705b]" /><h3 className="display mt-10 text-3xl font-semibold">Property visualization</h3><p className="mt-4 text-sm leading-6 text-[#1d2b20]/65">A clear visual direction for the changes you are considering, before decisions are made.</p><img src={ASSETS.concept} alt="Lush property visualization concept" className="mt-7 aspect-[1.35/1] w-full rounded-2xl object-cover" /></article></div><p className="mt-6 max-w-2xl text-xs leading-5 text-[#1d2b20]/60">Outdoor living and hardscape concepts are planning and visualization services. Licensed construction work is coordinated with qualified professionals when appropriate.</p></div></section>

    <section id="configurator" className="relative overflow-hidden bg-[#173221] py-24 text-white md:py-32"><div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_15%,rgba(163,204,161,0.26),transparent_30%),radial-gradient(circle_at_15%_90%,rgba(215,230,198,0.12),transparent_30%)]" /><div className="container relative"><SectionHeading eyebrow="Build your vision" light title={<>WHAT DO YOU WANT<br />TO FEEL OUTSIDE?</>} copy="Use these simple choices to shape a starting point for your conversation. It is an exploration—not a quote." />
      <div className="mt-14 grid gap-6 xl:grid-cols-[0.83fr_1.17fr]"><div className="rounded-[1.5rem] border border-white/15 bg-white/[0.06] p-6 md:p-8"><div><p className="text-sm font-semibold">Your space</p><div className="mt-4 flex flex-wrap gap-2">{properties.map(item => <button key={item} onClick={() => setProperty(item)} className={`rounded-full px-4 py-2.5 text-sm font-medium transition-colors ${property === item ? "bg-[#e6f0df] text-[#173221]" : "border border-white/20 text-white/72 hover:border-white/60"}`}>{item}</button>)}</div></div><div className="mt-8"><p className="text-sm font-semibold">Your style</p><div className="mt-4 flex flex-wrap gap-2">{styles.map(item => <button key={item} onClick={() => setStyle(item)} className={`rounded-full px-4 py-2.5 text-sm font-medium transition-colors ${style === item ? "bg-[#b9d3b5] text-[#173221]" : "border border-white/20 text-white/72 hover:border-white/60"}`}>{item}</button>)}</div></div><div className="mt-8"><p className="text-sm font-semibold">What matters most</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{features.map(item => <button key={item} onClick={() => toggleFeature(item)} className={`flex items-center justify-between rounded-xl border px-4 py-3 text-left text-sm transition-colors ${selectedFeatures.includes(item) ? "border-[#b9d3b5] bg-[#b9d3b5]/15 text-white" : "border-white/15 text-white/65 hover:border-white/50"}`}><span>{item}</span>{selectedFeatures.includes(item) && <Check size={16} className="text-[#b9d3b5]" />}</button>)}</div></div></div>
        <div className="relative min-h-[510px] overflow-hidden rounded-[1.5rem] border border-white/15"><img src={ASSETS.water} alt="Lush contemporary outdoor concept" className="absolute inset-0 h-full w-full object-cover transition-all duration-700" style={{ filter: style === "Modern" ? "saturate(.85) contrast(1.08)" : style === "Natural" ? "saturate(1.15) hue-rotate(-6deg)" : "none" }} /><div className="absolute inset-0 bg-gradient-to-t from-[#102015]/92 via-[#102015]/12 to-transparent" /><div className="relative flex min-h-[510px] flex-col justify-end p-7 md:p-9"><div className="max-w-xl"><p className="text-sm font-semibold text-[#d5e8cf]">Your Canyon concept</p><h3 className="display mt-3 text-4xl font-semibold leading-[0.92] md:text-5xl">A {style.toLowerCase()}<br />{property.toLowerCase()} with room to breathe.</h3><p className="mt-5 text-sm leading-7 text-white/78">{selectedSummary}</p><a href="#contact" className="mt-8 inline-block rounded-full bg-white px-5 py-3"><ArrowLink label="Discuss this concept" /></a></div></div></div></div></div></section>

    <section className="bg-[#102015] py-24 text-white md:py-32"><div className="container"><SectionHeading eyebrow="Concept studies" light title={<>MODERN DOESN'T<br />HAVE TO MEAN BARE.</>} copy="These illustrative studies layer shade, moving water, warm firelight, and materials that will look better—not just newer—with time." />
      <div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-12"><article className="group relative min-h-[500px] overflow-hidden rounded-[1.2rem] border border-white/10 bg-[#173221] text-white md:col-span-2 lg:col-span-7"><img src={ASSETS.water} alt="Garden concept with water feature" className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#102015]/90 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-7 md:p-9"><p className="text-sm font-semibold text-[#d5e8cf]">Pacific garden</p><h3 className="display mt-2 text-4xl font-bold leading-[0.9]">Water, shade,<br />and firelight.</h3><p className="mt-3 max-w-md text-sm leading-6 text-white/75">A lush outdoor room designed for a quiet change from afternoon canopy to evenings around the flame.</p></div></article><article className="group relative min-h-[500px] overflow-hidden rounded-[1.2rem] border border-white/10 bg-[#173221] text-white lg:col-span-5"><img src={ASSETS.patio} alt="Shadowed contemporary hardscape and outdoor room" className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#102015]/90 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-7 md:p-9"><p className="text-sm font-semibold text-[#d5e8cf]">Canyon courtyard</p><h3 className="display mt-2 text-4xl font-bold leading-[0.9]">Stone, shadow,<br />and green texture.</h3><p className="mt-3 text-sm leading-6 text-white/75">A contemporary hardscape sequence softened with full, site-aware planting.</p></div></article></div></div></section>

    <section id="process" className="bg-[#e0e7d9] py-24 md:py-32"><div className="container"><SectionHeading eyebrow="A thoughtful process" title={<>FROM FIRST IDEA<br />TO A REAL PLAN.</>} copy="The goal is simple: move from uncertainty to a clear, usable direction for your property." />
      <div className="mt-14 grid gap-4 md:grid-cols-3"><div className="rounded-[1.5rem] bg-[#f8f7f1] p-7 shadow-[0_14px_35px_rgba(35,52,38,0.08)]"><Sun className="text-[#52705b]" /><h3 className="mt-7 text-2xl font-semibold">Start with the site</h3><p className="mt-3 text-sm leading-6 text-[#1d2b20]/65">We talk through the existing space, your routines, and the moments you want it to support.</p></div><div className="rounded-[1.5rem] bg-[#f8f7f1] p-7 shadow-[0_14px_35px_rgba(35,52,38,0.08)]"><Leaf className="text-[#52705b]" /><h3 className="mt-7 text-2xl font-semibold">Shape the environment</h3><p className="mt-3 text-sm leading-6 text-[#1d2b20]/65">Planting, water, fire, paths, materials, and gathering areas begin to come together as one landscape.</p></div><div className="rounded-[1.5rem] bg-[#f8f7f1] p-7 shadow-[0_14px_35px_rgba(35,52,38,0.08)]"><Flame className="text-[#52705b]" /><h3 className="mt-7 text-2xl font-semibold">Refine the direction</h3><p className="mt-3 text-sm leading-6 text-[#1d2b20]/65">We clarify the concept and help coordinate next steps with appropriate qualified professionals when needed.</p></div></div></div></section>

    <section className="relative overflow-hidden bg-[#173221] py-24 text-white md:py-32"><img src={ASSETS.detail} alt="Environmental planting texture" className="absolute inset-y-0 right-0 h-full w-full object-cover opacity-25 md:w-1/2 md:opacity-65" /><div className="absolute inset-y-0 right-0 w-full bg-gradient-to-r from-[#173221] via-[#173221]/85 to-[#173221]/20 md:w-3/4" /><div className="container relative"><SectionHeading eyebrow="Design with the land" light title={<>A BETTER OUTDOOR<br />ENVIRONMENT STARTS HERE.</>} copy="Water-conscious planting, material durability, shade, and site conditions are not add-ons. They shape the way an outdoor space feels every day." /><div className="mt-12 grid max-w-2xl gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/15 bg-white/[0.07] p-5"><Leaf className="text-[#b9d3b5]" /><p className="mt-8 text-lg font-semibold">Plants that belong</p><p className="mt-2 text-sm leading-6 text-white/65">Living layers chosen with the climate and maintenance in mind.</p></div><div className="rounded-2xl border border-white/15 bg-white/[0.07] p-5"><Droplets className="text-[#b9d3b5]" /><p className="mt-8 text-lg font-semibold">Water that works</p><p className="mt-2 text-sm leading-6 text-white/65">Thoughtful irrigation concepts and water features with a sense of place.</p></div><div className="rounded-2xl border border-white/15 bg-white/[0.07] p-5"><Flame className="text-[#b9d3b5]" /><p className="mt-8 text-lg font-semibold">Evenings outside</p><p className="mt-2 text-sm leading-6 text-white/65">Light and warmth positioned for real gathering, not just a rendering.</p></div></div></div></section>

    <section className="bg-[#f4f2eb] py-24 md:py-32"><div className="container"><SectionHeading eyebrow="Rooted nearby" title={<>BUILT FOR SOUTHERN<br />CALIFORNIA LIVING.</>} copy="Canyon Outdoor is rooted in Orange County and shaped by the region's light, climate, material palette, and easy connection between indoors and out." /><div className="mt-14 grid overflow-hidden rounded-[1.5rem] border border-[#1d2b20]/10 lg:grid-cols-[1.2fr_0.8fr]"><div className="relative min-h-[400px]"><MapView initialCenter={{ lat: 33.6704, lng: -117.822 } as google.maps.LatLngLiteral} initialZoom={10} className="map-canvas h-full min-h-[400px] w-full" /><div className="absolute left-5 top-5 rounded-full bg-[#f8f7f1]/90 px-4 py-2 text-sm font-semibold text-[#173221] shadow-sm backdrop-blur">Orange County, CA</div></div><div className="flex flex-col justify-between bg-[#e0e7d9] p-7 md:p-10"><div><p className="text-2xl font-semibold">Close to the land.</p><p className="mt-4 max-w-sm text-sm leading-7 text-[#1d2b20]/65">For a location not listed, an inquiry is the best way to see if the project is a fit.</p></div><div className="mt-12 flex flex-wrap gap-2">{["Huntington Beach", "Newport Beach", "Costa Mesa", "Irvine", "Fountain Valley", "Anaheim"].map(areaName => <span key={areaName} className="rounded-full border border-[#1d2b20]/15 bg-white/40 px-3 py-2 text-xs text-[#1d2b20]/75">{areaName}</span>)}</div></div></div></div></section>

    <section id="about" className="bg-[#e0e7d9] py-24 md:py-32"><div className="container grid gap-12 lg:grid-cols-[0.42fr_0.58fr]"><div><BrandLockup /><p className="mt-7 max-w-xs text-base leading-7 text-[#1d2b20]/66">A growing studio with a more complete view of what outdoor spaces can become.</p></div><div><h2 className="display max-w-4xl text-5xl font-bold leading-[0.88] md:text-7xl">WE SEE MORE<br />THAN A YARD.</h2><p className="mt-8 max-w-2xl text-lg leading-8 text-[#1d2b20]/70">Canyon Outdoor approaches exterior space as an extension of the property and the people who use it. We consider sun paths, shade, planting depth, water, material character, and the rituals that bring a landscape to life.</p><a href="#contact" className="mt-9 inline-block"><ArrowLink label="Start with a conversation" /></a></div></div></section>

    <section id="contact" className="soft-mesh relative overflow-hidden py-24 md:py-32"><div className="container"><SectionHeading eyebrow="Project inquiry" title={<>LET'S CREATE YOUR<br />OUTDOOR SPACE.</>} copy="Share what you are imagining. This short guided inquiry gives us a helpful place to start." />
      <div className="mt-14 overflow-hidden rounded-[1.5rem] border border-[#1d2b20]/10 bg-[#f9f8f3] shadow-[0_25px_70px_rgba(35,52,38,0.12)]">{submitted ? <div className="grid min-h-[460px] place-items-center p-8 text-center"><div className="max-w-lg"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#173221] text-white"><Check size={25} /></div><h3 className="display mt-7 text-5xl font-semibold leading-[0.92]">WE'VE GOT IT.</h3><p className="mx-auto mt-5 max-w-md text-base leading-7 text-[#1d2b20]/65">Thanks for reaching out to Canyon Outdoor. We’ll review your project information and get back to you.</p><button onClick={() => { setSubmitted(false); setStep(0); }} className="mt-8 rounded-full border border-[#1d2b20]/20 px-5 py-3 text-sm font-semibold">Start another inquiry</button></div></div> : <form onSubmit={submitInquiry} className="grid lg:grid-cols-[0.3fr_0.7fr]"><aside className="bg-[#173221] p-7 text-white md:p-9"><BrandLockup light compact /><p className="mt-10 text-lg leading-8 text-white/72">A few details now make a more useful first conversation later.</p><div className="mt-12 flex gap-2">{[0, 1, 2, 3, 4, 5].map(item => <button type="button" key={item} onClick={() => setStep(item)} className={`h-2.5 rounded-full transition-all ${step === item ? "w-8 bg-[#b9d3b5]" : "w-2.5 bg-white/25"}`} aria-label={`Go to form step ${item + 1}`} />)}</div></aside><div className="min-h-[480px] p-7 md:p-10 lg:p-14">
        {step === 0 && <div><h3 className="display text-4xl font-semibold leading-[0.95] md:text-5xl">WHAT ARE YOU<br />IMAGINING?</h3><p className="mt-4 text-sm leading-6 text-[#1d2b20]/60">Choose anything that feels relevant right now.</p><div className="mt-8 grid gap-2 sm:grid-cols-2">{inquiryTypes.map(item => <button type="button" key={item} onClick={() => toggleInquiry(item)} className={`flex items-center justify-between rounded-xl border p-4 text-left text-sm font-semibold transition-colors ${inquiryType.includes(item) ? "border-[#35563d] bg-[#e0e7d9]" : "border-[#1d2b20]/15 hover:border-[#35563d]"}`}><span>{item}</span>{inquiryType.includes(item) && <Check size={17} className="text-[#35563d]" />}</button>)}</div></div>}
        {step === 1 && <div><h3 className="display text-4xl font-semibold leading-[0.95] md:text-5xl">WHAT KIND OF<br />PROPERTY IS IT?</h3><div className="mt-8 grid gap-3 sm:grid-cols-3">{["Residential", "Commercial", "Other"].map(item => <button type="button" key={item} onClick={() => setPropertyType(item)} className={`min-h-32 rounded-2xl border p-5 text-left text-lg font-semibold transition-colors ${propertyType === item ? "border-[#35563d] bg-[#e0e7d9]" : "border-[#1d2b20]/15 hover:border-[#35563d]"}`}>{item}</button>)}</div></div>}
        {step === 2 && <div><h3 className="display text-4xl font-semibold leading-[0.95] md:text-5xl">WHERE IS THE<br />PROJECT LOCATED?</h3><p className="mt-4 text-sm leading-6 text-[#1d2b20]/60">A city or general neighborhood is enough for a first look.</p><input value={area} onChange={event => setArea(event.target.value)} placeholder="e.g. Costa Mesa, CA" className="mt-10 w-full border-b border-[#1d2b20]/25 bg-transparent py-4 text-2xl font-semibold outline-none placeholder:text-[#1d2b20]/28 focus:border-[#35563d]" /></div>}
        {step === 3 && <div><h3 className="display text-4xl font-semibold leading-[0.95] md:text-5xl">WHAT SHOULD<br />FEEL DIFFERENT?</h3><textarea value={details} onChange={event => setDetails(event.target.value)} placeholder="Tell us about the site, what is not working now, and the experience you are hoping to create." className="mt-8 min-h-52 w-full resize-none rounded-2xl border border-[#1d2b20]/15 bg-transparent p-5 text-sm leading-7 outline-none placeholder:text-[#1d2b20]/35 focus:border-[#35563d]" /></div>}
        {step === 4 && <div><h3 className="display text-4xl font-semibold leading-[0.95] md:text-5xl">SHOW US WHAT<br />INSPIRES YOU.</h3><label className="mt-8 flex min-h-48 flex-col items-center justify-center rounded-2xl border border-dashed border-[#1d2b20]/30 bg-[#e0e7d9]/55 p-6 text-center transition-colors hover:bg-[#e0e7d9]"><Sparkles size={22} className="mb-4 text-[#35563d]" /><span className="text-sm font-semibold">{fileName || "Choose an image or drop it here"}</span><span className="mt-2 text-xs text-[#1d2b20]/55">A reference photo or simple site image is welcome.</span><input type="file" accept="image/*" className="sr-only" onChange={event => setFileName(event.target.files?.[0]?.name || "")} /></label></div>}
        {step === 5 && <div><h3 className="display text-4xl font-semibold leading-[0.95] md:text-5xl">HOW CAN WE<br />REACH YOU?</h3><div className="mt-8 grid gap-4 sm:grid-cols-2"><input required placeholder="Name" className="border-b border-[#1d2b20]/25 bg-transparent py-4 text-sm outline-none placeholder:text-[#1d2b20]/40 focus:border-[#35563d]" /><input required type="email" placeholder="Email address" className="border-b border-[#1d2b20]/25 bg-transparent py-4 text-sm outline-none placeholder:text-[#1d2b20]/40 focus:border-[#35563d]" /><input placeholder="Phone (optional)" className="border-b border-[#1d2b20]/25 bg-transparent py-4 text-sm outline-none placeholder:text-[#1d2b20]/40 focus:border-[#35563d]" /><input placeholder="Best time to connect (optional)" className="border-b border-[#1d2b20]/25 bg-transparent py-4 text-sm outline-none placeholder:text-[#1d2b20]/40 focus:border-[#35563d]" /></div></div>}
        <div className="mt-12 flex items-center justify-between border-t border-[#1d2b20]/12 pt-5"><button type="button" onClick={prevStep} disabled={step === 0} className="flex items-center gap-1 text-sm font-semibold disabled:opacity-25"><ChevronLeft size={16} />Back</button>{step < 5 ? <button type="button" onClick={nextStep} className="flex items-center gap-2 rounded-full bg-[#173221] px-5 py-3 text-sm font-semibold text-white">Continue <ChevronRight size={16} /></button> : <button type="submit" className="flex items-center gap-2 rounded-full bg-[#35563d] px-5 py-3 text-sm font-semibold text-white">Send inquiry <ArrowRight size={16} /></button>}</div></div></form>}</div></div></section>

    <footer className="bg-[#173221] py-12 text-white"><div className="container flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><BrandLockup light /><p className="mt-5 max-w-xs text-sm leading-6 text-white/60">Landscape design, outdoor living concepts, hardscape concepts, and property visualization.</p></div><div className="flex flex-wrap gap-x-5 gap-y-3 text-sm text-white/65">{navLinks.map(link => <a key={link} href={`#${link.toLowerCase()}`} className="hover:text-white">{link}</a>)}</div><p className="text-xs text-white/45">© 2026 Canyon Outdoor</p></div></footer>
  </main>;
}
