/** Canyon Outdoor Privacy Policy: readable, site-specific working draft for the public website and its inquiry flow. */
import { PageIntro, SiteFooter, SiteHeader } from "@/components/SiteChrome";

export default function Privacy() {
  return <><SiteHeader /><main id="main-content" className="bg-[#f4f2eb] pt-32 text-[#1d2b20] md:pt-40"><section className="pb-24 md:pb-32"><div className="container"><PageIntro eyebrow="Legal" title={<>PRIVACY<br />POLICY.</>} copy="Effective August 17, 2026. This policy explains how Canyon Outdoor handles information collected through this website." />
    <article className="mt-14 max-w-4xl rounded-[1.5rem] border border-[#1d2b20]/10 bg-[#fbfaf6] p-7 shadow-[0_16px_42px_rgba(35,52,38,0.08)] md:p-12"><div className="prose prose-lg max-w-none text-[#1d2b20] prose-headings:font-[DM_Sans] prose-headings:font-bold prose-headings:text-[#173221] prose-p:leading-8 prose-li:leading-8 prose-a:text-[#35563d]"><p className="lead">Canyon Outdoor respects your privacy. This Privacy Policy applies to information collected through the Canyon Outdoor website and its project inquiry experience.</p>
      <h2>Information we collect</h2><p>When you use the project inquiry form, we may collect the information you choose to provide, including your name, email address, phone number, general project location, property type, project interests, written project details, and an optional public reference link. We may also receive limited technical information that is typically provided by a browser or device, such as an IP address, browser type, referring page, and general usage information.</p>
      <h2>How we use information</h2><p>We use inquiry information to respond to you, understand your project, assess whether a project may be a fit, prepare for conversations, improve the website, and protect the security and reliability of our services. We may use aggregated website analytics to understand how visitors use the site. We do not use your inquiry information to build advertising audiences unrelated to Canyon Outdoor.</p>
      <h2>How we share information</h2><p>We may share information with service providers that support website hosting, analytics, communications, file storage, or other business operations. Those providers may process information only as needed to provide services to us or comply with law. We may also disclose information when reasonably necessary to protect our rights, prevent fraud or misuse, respond to lawful requests, or complete a business transaction such as a merger or acquisition.</p>
      <h2>Sales and targeted advertising</h2><p>Canyon Outdoor does not sell personal information collected through this website. We also do not share personal information for cross-context behavioral advertising through this website.</p>
      <h2>Data retention and security</h2><p>We retain information for as long as reasonably necessary for the purposes described in this policy, including responding to inquiries, maintaining business records, resolving disputes, and meeting legal obligations. We use reasonable administrative, technical, and organizational safeguards designed to protect information. No internet transmission or storage system can be guaranteed completely secure.</p>
      <h2>Your choices and privacy rights</h2><p>You may request access to, correction of, or deletion of personal information we hold about you, subject to applicable law and legitimate business or legal requirements. California residents may have additional rights to know, delete, correct, and limit certain uses of personal information. To make a request, use the Contact button on this website and clearly identify the request. We may need to verify your identity before completing it.</p>
      <h2>Children's privacy</h2><p>This website is not directed to children under 13, and Canyon Outdoor does not knowingly collect personal information from children under 13. If you believe a child has provided personal information through the site, please contact us through the website so we can take appropriate action.</p>
      <h2>Third-party links and changes</h2><p>This website may link to third-party sites or services. Their privacy practices are governed by their own policies, not this one. We may update this Privacy Policy from time to time. Any changes will be posted on this page with a revised effective date.</p>
      <h2>Contact us</h2><p>For questions or privacy requests, select the Contact button in the top navigation and include enough detail for us to understand your request.</p>
    </div></article></div></section></main><SiteFooter /></>;
}
