/** Canyon Outdoor Process page: a clear route from site observation to a build-ready visual direction. */
import { Droplets, Flame, Leaf, Sun } from "lucide-react";
import { ASSETS } from "@/lib/site";
import { PageIntro, SiteFooter, SiteHeader } from "@/components/SiteChrome";

export default function Process() {
  return <><SiteHeader /><main className="bg-[#f4f2eb] pt-32 text-[#1d2b20] md:pt-40"><section className="pb-24 md:pb-32"><div className="container"><PageIntro eyebrow="A thoughtful process" title={<>FROM FIRST IDEA<br />TO A REAL PLAN.</>} copy="The goal is simple: move from uncertainty to a clear, usable direction for your property." />
    <div className="mt-14 grid gap-4 md:grid-cols-3"><div className="rounded-[1.5rem] bg-[#e0e7d9] p-7 shadow-[0_14px_35px_rgba(35,52,38,0.08)]"><Sun className="text-[#52705b]" /><h2 className="mt-7 text-2xl font-semibold">Start with the site</h2><p className="mt-3 text-sm leading-6 text-[#1d2b20]/65">We talk through the existing space, your routines, sun exposure, and the moments you want it to support.</p></div><div className="rounded-[1.5rem] bg-[#e0e7d9] p-7 shadow-[0_14px_35px_rgba(35,52,38,0.08)]"><Leaf className="text-[#52705b]" /><h2 className="mt-7 text-2xl font-semibold">Shape the environment</h2><p className="mt-3 text-sm leading-6 text-[#1d2b20]/65">Planting, water, fire, paths, materials, and gathering areas begin to come together as one landscape.</p></div><div className="rounded-[1.5rem] bg-[#e0e7d9] p-7 shadow-[0_14px_35px_rgba(35,52,38,0.08)]"><Flame className="text-[#52705b]" /><h2 className="mt-7 text-2xl font-semibold">Refine the direction</h2><p className="mt-3 text-sm leading-6 text-[#1d2b20]/65">We clarify the concept and help coordinate next steps with appropriate qualified professionals when needed.</p></div></div></div></section>
    <section className="relative overflow-hidden bg-[#173221] py-24 text-white md:py-32"><img src={ASSETS.detail} alt="Environmental planting texture" className="absolute inset-y-0 right-0 h-full w-full object-cover opacity-25 md:w-1/2 md:opacity-65" /><div className="absolute inset-y-0 right-0 w-full bg-gradient-to-r from-[#173221] via-[#173221]/85 to-[#173221]/20 md:w-3/4" /><div className="container relative"><PageIntro eyebrow="Design with the land" light title={<>A BETTER OUTDOOR<br />ENVIRONMENT STARTS HERE.</>} copy="Water-conscious planting, material durability, shade, and site conditions shape the way an outdoor space feels every day." /><div className="mt-12 grid max-w-2xl gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/15 bg-white/[0.07] p-5"><Leaf className="text-[#b9d3b5]" /><p className="mt-8 text-lg font-semibold">Plants that belong</p><p className="mt-2 text-sm leading-6 text-white/65">Living layers chosen with the climate and maintenance in mind.</p></div><div className="rounded-2xl border border-white/15 bg-white/[0.07] p-5"><Droplets className="text-[#b9d3b5]" /><p className="mt-8 text-lg font-semibold">Water that works</p><p className="mt-2 text-sm leading-6 text-white/65">Thoughtful irrigation concepts and water features with a sense of place.</p></div><div className="rounded-2xl border border-white/15 bg-white/[0.07] p-5"><Flame className="text-[#b9d3b5]" /><p className="mt-8 text-lg font-semibold">Evenings outside</p><p className="mt-2 text-sm leading-6 text-white/65">Light and warmth positioned for real gathering, not just a rendering.</p></div></div></div></section>
  </main><SiteFooter /></>;
}
