/** Canyon Outdoor Terms of Service: readable, site-specific working draft governing use of the public website and inquiry flow. */
import { PageIntro, SiteFooter, SiteHeader } from "@/components/SiteChrome";

export default function Terms() {
  return <><SiteHeader /><main id="main-content" className="bg-[#f4f2eb] pt-32 text-[#1d2b20] md:pt-40"><section className="pb-24 md:pb-32"><div className="container"><PageIntro eyebrow="Legal" title={<>TERMS OF<br />SERVICE.</>} copy="Effective August 17, 2026. These terms govern your use of the Canyon Outdoor website and its inquiry tools." />
    <article className="mt-14 max-w-4xl rounded-[1.5rem] border border-[#1d2b20]/10 bg-[#fbfaf6] p-7 shadow-[0_16px_42px_rgba(35,52,38,0.08)] md:p-12"><div className="prose prose-lg max-w-none text-[#1d2b20] prose-headings:font-[DM_Sans] prose-headings:font-bold prose-headings:text-[#173221] prose-p:leading-8 prose-li:leading-8 prose-a:text-[#35563d]"><p className="lead">Welcome to the Canyon Outdoor website. By accessing or using this site, you agree to these Terms of Service. If you do not agree, please do not use the site.</p>
      <h2>Purpose of this website</h2><p>Canyon Outdoor presents landscape design, outdoor living concepts, hardscape concepts, property visualization, and related information. The website and its inquiry tools are provided for general informational and communication purposes. Images, plans, concepts, and visual studies are illustrative and may not represent completed work, final scope, site conditions, pricing, engineering, permitting, or construction details.</p>
      <h2>No construction contract or professional advice</h2><p>Submitting an inquiry, using a configurator, receiving a concept, or communicating through this website does not create a construction contract, design contract, professional-client relationship, or commitment to provide services. Any project engagement, scope, timing, fees, deliverables, and responsibilities must be confirmed in a separate written agreement signed by the appropriate parties. You should consult qualified professionals for engineering, permitting, construction, legal, financial, or site-specific advice.</p>
      <h2>Acceptable use</h2><p>You may use this website only for lawful purposes and in a way that does not interfere with its security, operation, or the rights of others. You may not attempt to gain unauthorized access to the site, introduce malicious code, scrape or copy content at scale, impersonate another person, submit false or misleading information, or use the site for a purpose that violates applicable law.</p>
      <h2>Your submissions</h2><p>You are responsible for information, public reference links, and other materials you submit through the inquiry process. By submitting them, you represent that you have the right to do so and grant Canyon Outdoor permission to review and use them solely to respond to your inquiry, evaluate a potential project, and operate or improve its services. Do not submit confidential information that you do not want Canyon Outdoor to receive.</p>
      <h2>Intellectual property</h2><p>The website design, text, images, logos, graphics, concepts, and other content are owned by Canyon Outdoor or its licensors and are protected by applicable intellectual-property laws. You may view and use the content for personal, noncommercial consideration of Canyon Outdoor's services. You may not reproduce, distribute, modify, publish, or create derivative works from site content without prior written permission, except where applicable law allows.</p>
      <h2>Third-party services</h2><p>The website may rely on third-party services, links, maps, analytics, hosting providers, or other integrations. Canyon Outdoor does not control those third parties and is not responsible for their content, availability, privacy practices, or terms. Your use of third-party services is subject to their own policies.</p>
      <h2>Disclaimers and limitation of liability</h2><p>The website is provided on an “as is” and “as available” basis. To the fullest extent permitted by law, Canyon Outdoor disclaims warranties of any kind, whether express, implied, or statutory, including warranties of merchantability, fitness for a particular purpose, title, and noninfringement. Canyon Outdoor does not guarantee that the website will be uninterrupted, error-free, secure, or suitable for every purpose.</p><p>To the fullest extent permitted by law, Canyon Outdoor and its owners, employees, contractors, and service providers will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages arising from or related to your use of, or inability to use, the website. Where liability cannot be excluded, it will be limited to the maximum extent permitted by applicable law.</p>
      <h2>Indemnification</h2><p>You agree to defend, indemnify, and hold harmless Canyon Outdoor and its owners, employees, contractors, and service providers from claims, losses, liabilities, damages, costs, and expenses arising out of your violation of these Terms, misuse of the website, or submission of materials that infringe another person's rights.</p>
      <h2>Governing law and changes</h2><p>These Terms are governed by the laws of the State of California, without regard to conflict-of-law principles. We may update these Terms from time to time. Updated terms will be posted on this page with a revised effective date. Your continued use of the website after an update means you accept the updated Terms.</p>
      <h2>Contact</h2><p>For questions about these Terms, select the Contact button in the top navigation and provide a brief description of your question.</p>
    </div></article></div></section></main><SiteFooter /></>;
}
