/** Canyon Outdoor Work page: show property-specific transformation and a complete modern pool garden without UI clutter. */
import { useState } from "react";
import { Droplets, Flame, Leaf, MoveHorizontal } from "lucide-react";
import { ASSETS } from "@/lib/site";
import { PageIntro, SiteFooter, SiteHeader } from "@/components/SiteChrome";
import { QuickContactForm } from "@/components/QuickContactForm";

export default function Work() {
  const [comparison, setComparison] = useState(50);
  return <><SiteHeader /><main className="bg-[#f4f2eb] pt-32 text-[#1d2b20] md:pt-40">
    <section className="pb-24 md:pb-32"><div className="container"><PageIntro eyebrow="Visualize before you build" title={<>A CLEARER WAY<br />TO SEE YOUR SPACE.</>} copy="A thoughtful concept keeps the house, light, circulation, and character of the property in view, then makes the landscape opportunity tangible." />
      <div className="mt-14 grid gap-7 lg:grid-cols-[1fr_300px]"><div className="relative aspect-[1.25/1] overflow-hidden rounded-[1.5rem] bg-[#d8ddd0] shadow-[0_18px_45px_rgba(36,59,40,0.11)] md:aspect-[1.7/1]"><img src={ASSETS.before} alt="Existing residential property" className="absolute inset-0 h-full w-full object-cover brightness-90" /><div className="absolute inset-y-0 left-0 overflow-hidden" style={{ width: `${comparison}%` }}><img src={ASSETS.concept} alt="Canyon Outdoor redesign concept for the same home" className="h-full max-w-none w-[calc(100vw-2.5rem)] object-cover md:w-[min(100%,1000px)]" /></div><div className="absolute inset-y-0 z-10 w-px bg-white shadow-[0_0_0_1px_rgba(0,0,0,.16)]" style={{ left: `${comparison}%` }}><button aria-label="Drag before and after comparison" className="absolute left-1/2 top-1/2 grid h-12 w-12 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-white text-[#1d2b20] shadow-lg" onPointerDown={event => { const parent = event.currentTarget.parentElement?.parentElement; if (!parent) return; const move = (moveEvent: PointerEvent) => { const rect = parent.getBoundingClientRect(); setComparison(Math.max(3, Math.min(97, ((moveEvent.clientX - rect.left) / rect.width) * 100))); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", () => window.removeEventListener("pointermove", move), { once: true }); }}><MoveHorizontal size={18} /></button></div><span className="absolute left-5 top-5 rounded-full bg-[#173221]/80 px-3 py-1.5 text-xs font-semibold text-white backdrop-blur">Canyon concept</span><span className="absolute right-5 top-5 rounded-full bg-white/85 px-3 py-1.5 text-xs font-semibold text-[#173221] backdrop-blur">Existing property</span></div>
        <aside className="rounded-[1.5rem] bg-[#173221] p-7 text-white md:p-8"><Leaf className="text-[#b9d3b5]" size={22} /><h2 className="display mt-8 text-3xl font-semibold leading-[0.94]">KEEP THE HOME.<br />GROW THE OUTDOORS.</h2><p className="mt-5 text-sm leading-7 text-white/70">The redesigned concept uses the same architecture and vantage point, then brings in layered planting, a water element, clear paths, and firelight.</p></aside></div>
    </div></section>
    <section className="bg-[#102015] py-24 text-white md:py-32"><div className="container"><PageIntro eyebrow="Outdoor living concept" light title={<>ONE COMPLETE<br />OUTDOOR ENVIRONMENT.</>} copy="A full outdoor living concept sees the whole picture: a pool to cool off, a fire to gather around, a place to cook, and planting that gives every zone shade, texture, and privacy." />
      <article className="relative mt-14 min-h-[680px] overflow-hidden rounded-[1.4rem] border border-white/10 bg-[#173221] md:min-h-[760px]"><img src={ASSETS.poolLiving} alt="Full contemporary outdoor living space with pool, fire feature, kitchen, and lush planting" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(10,28,17,0.88)_0%,rgba(10,28,17,0.48)_36%,rgba(10,28,17,0.05)_68%),linear-gradient(0deg,rgba(10,28,17,0.66)_0%,transparent_45%)]" />
        <div className="relative flex min-h-[680px] max-w-xl flex-col justify-end p-7 md:min-h-[760px] md:p-12"><div className="rounded-[1.25rem] border border-white/15 bg-[#102015]/55 p-6 backdrop-blur-md md:p-7"><div className="flex items-center gap-2 text-sm font-semibold text-[#d5e8cf]"><Droplets size={17} /> Pool + garden living</div><h2 className="display mt-5 text-4xl font-bold leading-[0.9] md:text-6xl">THE WHOLE SPACE,<br />WORKING TOGETHER.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-white/75">A deep-green pool garden designed as one complete outdoor room. Water at the center, a fire feature for evening, an outdoor kitchen for gathering, and dense California planting that makes every edge feel alive.</p><div className="mt-7 flex flex-wrap gap-x-5 gap-y-3 text-sm text-white/80"><span className="inline-flex items-center gap-2"><Droplets size={15} className="text-[#b9d3b5]" />Reflective pool</span><span className="inline-flex items-center gap-2"><Flame size={15} className="text-[#b9d3b5]" />Fire lounge</span><span className="inline-flex items-center gap-2"><Leaf size={15} className="text-[#b9d3b5]" />Layered planting</span></div></div></div>
      </article></div></section>
  </main><QuickContactForm /><SiteFooter /></>;
}
