/** Canyon Outdoor contact modal: a calm, detailed inquiry flow that opens above a blurred site and gathers a useful project overview. */
import { FormEvent, useEffect, useState } from "react";
import { Check, ChevronLeft, ChevronRight, Sparkles, X } from "lucide-react";

const inquiryTypes = ["Landscape design", "Outdoor living", "Hardscape concept", "Backyard transformation", "Property visualization", "Not sure yet"];

export function ContactModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [step, setStep] = useState(0); const [inquiryType, setInquiryType] = useState<string[]>([]); const [propertyType, setPropertyType] = useState(""); const [area, setArea] = useState(""); const [details, setDetails] = useState(""); const [fileName, setFileName] = useState(""); const [submitted, setSubmitted] = useState(false);
  const toggleInquiry = (item: string) => setInquiryType(current => current.includes(item) ? current.filter(value => value !== item) : [...current, item]);
  const reset = () => { setStep(0); setInquiryType([]); setPropertyType(""); setArea(""); setDetails(""); setFileName(""); setSubmitted(false); };
  const dismiss = () => { reset(); onClose(); };
  useEffect(() => { if (!open) return; const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") dismiss(); }; window.addEventListener("keydown", closeOnEscape); return () => window.removeEventListener("keydown", closeOnEscape); }, [open]);
  if (!open) return null;
  const submit = (event: FormEvent) => { event.preventDefault(); setSubmitted(true); };

  return <div className="fixed inset-0 z-[70] grid place-items-center p-4" role="dialog" aria-modal="true" aria-labelledby="contact-dialog-title"><button className="absolute inset-0 bg-[#0b1710]/55 backdrop-blur-md" onClick={dismiss} aria-label="Close contact form" /><div className="relative max-h-[calc(100vh-2rem)] w-full max-w-4xl overflow-y-auto rounded-[1.5rem] border border-white/10 bg-[#f8f7f1] shadow-[0_30px_90px_rgba(3,12,7,0.45)]"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-[#1d2b20]/10 bg-[#f8f7f1]/96 px-6 py-4 backdrop-blur md:px-8"><div><p className="eyebrow text-[#52705b]">Project inquiry</p><p className="mt-1 text-sm font-semibold text-[#1d2b20]">Canyon Outdoor</p></div><button onClick={dismiss} className="grid h-10 w-10 place-items-center rounded-full bg-[#173221] text-white" aria-label="Close contact form"><X size={18} /></button></div>{submitted ? <div className="grid min-h-[520px] place-items-center p-8 text-center md:p-14"><div className="max-w-lg"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#173221] text-white"><Check size={25} /></div><h2 id="contact-dialog-title" className="display mt-7 text-5xl font-semibold leading-[0.92]">WE'VE GOT IT.</h2><p className="mx-auto mt-5 max-w-md text-base leading-7 text-[#1d2b20]/65">Thanks for reaching out to Canyon Outdoor. We will review your project information and get back to you.</p><button onClick={dismiss} className="mt-8 rounded-full bg-[#173221] px-5 py-3 text-sm font-semibold text-white">Close</button></div></div> : <form onSubmit={submit} className="grid lg:grid-cols-[0.3fr_0.7fr]"><aside className="bg-[#173221] p-7 text-white md:p-9"><p className="display text-4xl font-bold leading-none">0{step + 1}<span className="text-white/30">/06</span></p><p className="mt-7 max-w-xs text-sm leading-7 text-white/70">A few details now help us begin a more useful conversation about your outdoor space.</p><div className="mt-12 flex gap-2">{[0, 1, 2, 3, 4, 5].map(item => <button type="button" key={item} onClick={() => setStep(item)} className={`h-2.5 rounded-full transition-all ${step === item ? "w-8 bg-[#b9d3b5]" : "w-2.5 bg-white/25"}`} aria-label={`Go to form step ${item + 1}`} />)}</div></aside><div className="min-h-[470px] p-7 md:p-10 lg:p-12">
    {step === 0 && <div><h2 id="contact-dialog-title" className="display text-4xl font-semibold leading-[0.95] md:text-5xl">WHAT ARE YOU<br />IMAGINING?</h2><p className="mt-4 text-sm leading-6 text-[#1d2b20]/60">Choose anything that feels relevant right now.</p><div className="mt-8 grid gap-2 sm:grid-cols-2">{inquiryTypes.map(item => <button type="button" key={item} onClick={() => toggleInquiry(item)} className={`flex items-center justify-between rounded-xl border p-4 text-left text-sm font-semibold transition-colors ${inquiryType.includes(item) ? "border-[#35563d] bg-[#e0e7d9]" : "border-[#1d2b20]/15 hover:border-[#35563d]"}`}><span>{item}</span>{inquiryType.includes(item) && <Check size={17} className="text-[#35563d]" />}</button>)}</div></div>}
    {step === 1 && <div><h2 id="contact-dialog-title" className="display text-4xl font-semibold leading-[0.95] md:text-5xl">WHAT KIND OF<br />PROPERTY IS IT?</h2><div className="mt-8 grid gap-3 sm:grid-cols-3">{["Residential", "Commercial", "Other"].map(item => <button type="button" key={item} onClick={() => setPropertyType(item)} className={`min-h-32 rounded-2xl border p-5 text-left text-lg font-semibold transition-colors ${propertyType === item ? "border-[#35563d] bg-[#e0e7d9]" : "border-[#1d2b20]/15 hover:border-[#35563d]"}`}>{item}</button>)}</div></div>}
    {step === 2 && <div><h2 id="contact-dialog-title" className="display text-4xl font-semibold leading-[0.95] md:text-5xl">WHERE IS THE<br />PROJECT LOCATED?</h2><p className="mt-4 text-sm leading-6 text-[#1d2b20]/60">A city or general neighborhood is enough for a first look.</p><input value={area} onChange={event => setArea(event.target.value)} placeholder="e.g. Costa Mesa, CA" className="mt-10 w-full border-b border-[#1d2b20]/25 bg-transparent py-4 text-2xl font-semibold outline-none placeholder:text-[#1d2b20]/28 focus:border-[#35563d]" /></div>}
    {step === 3 && <div><h2 id="contact-dialog-title" className="display text-4xl font-semibold leading-[0.95] md:text-5xl">WHAT SHOULD<br />FEEL DIFFERENT?</h2><textarea value={details} onChange={event => setDetails(event.target.value)} placeholder="Tell us about the site, what is not working now, and the experience you are hoping to create." className="mt-8 min-h-52 w-full resize-none rounded-2xl border border-[#1d2b20]/15 bg-transparent p-5 text-sm leading-7 outline-none placeholder:text-[#1d2b20]/35 focus:border-[#35563d]" /></div>}
    {step === 4 && <div><h2 id="contact-dialog-title" className="display text-4xl font-semibold leading-[0.95] md:text-5xl">SHOW US WHAT<br />INSPIRES YOU.</h2><label className="mt-8 flex min-h-48 flex-col items-center justify-center rounded-2xl border border-dashed border-[#1d2b20]/30 bg-[#e0e7d9]/55 p-6 text-center transition-colors hover:bg-[#e0e7d9]"><Sparkles size={22} className="mb-4 text-[#35563d]" /><span className="text-sm font-semibold">{fileName || "Choose an image or drop it here"}</span><span className="mt-2 text-xs text-[#1d2b20]/55">A reference photo or simple site image is welcome.</span><input type="file" accept="image/*" className="sr-only" onChange={event => setFileName(event.target.files?.[0]?.name || "")} /></label></div>}
    {step === 5 && <div><h2 id="contact-dialog-title" className="display text-4xl font-semibold leading-[0.95] md:text-5xl">HOW CAN WE<br />REACH YOU?</h2><div className="mt-8 grid gap-4 sm:grid-cols-2"><input required placeholder="Name" className="border-b border-[#1d2b20]/25 bg-transparent py-4 text-sm outline-none placeholder:text-[#1d2b20]/40 focus:border-[#35563d]" /><input required type="email" placeholder="Email address" className="border-b border-[#1d2b20]/25 bg-transparent py-4 text-sm outline-none placeholder:text-[#1d2b20]/40 focus:border-[#35563d]" /><input placeholder="Phone (optional)" className="border-b border-[#1d2b20]/25 bg-transparent py-4 text-sm outline-none placeholder:text-[#1d2b20]/40 focus:border-[#35563d]" /><input placeholder="Best time to connect (optional)" className="border-b border-[#1d2b20]/25 bg-transparent py-4 text-sm outline-none placeholder:text-[#1d2b20]/40 focus:border-[#35563d]" /></div><p className="mt-6 text-xs leading-5 text-[#1d2b20]/55">This prototype confirms the inquiry on screen. Connect a secure form delivery service before collecting live project details.</p></div>}
    <div className="mt-12 flex items-center justify-between border-t border-[#1d2b20]/12 pt-5"><button type="button" onClick={() => setStep(current => Math.max(0, current - 1))} disabled={step === 0} className="flex items-center gap-1 text-sm font-semibold disabled:opacity-25"><ChevronLeft size={16} />Back</button>{step < 5 ? <button type="button" onClick={() => setStep(current => Math.min(5, current + 1))} className="flex items-center gap-2 rounded-full bg-[#173221] px-5 py-3 text-sm font-semibold text-white">Continue <ChevronRight size={16} /></button> : <button type="submit" className="rounded-full bg-[#35563d] px-5 py-3 text-sm font-semibold text-white">Send inquiry</button>}</div></div></form>}</div></div>;
}
