/** Canyon Outdoor contact modal: a validated inquiry flow that sends structured project information to the protected server endpoint. */
import { FormEvent, useEffect, useState } from "react";
import { Check, ChevronLeft, ChevronRight, Link as LinkIcon, X } from "lucide-react";
import { trpc } from "@/lib/trpc";

const inquiryTypes = ["Landscape design", "Outdoor living", "Hardscape concept", "Backyard transformation", "Property visualization", "Not sure yet"] as const;
type InquiryType = (typeof inquiryTypes)[number];
const propertyTypes = ["Residential", "Commercial", "Other"] as const;

export function ContactModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [step, setStep] = useState(0); const [requestedServices, setRequestedServices] = useState<InquiryType[]>([]); const [propertyType, setPropertyType] = useState<(typeof propertyTypes)[number] | "">(""); const [location, setLocation] = useState(""); const [projectDetails, setProjectDetails] = useState(""); const [inspirationUrl, setInspirationUrl] = useState(""); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [phone, setPhone] = useState(""); const [bestContactTime, setBestContactTime] = useState(""); const [formError, setFormError] = useState(""); const [submitted, setSubmitted] = useState(false);
  const inquiry = trpc.inquiry.submit.useMutation({ onSuccess: () => { setSubmitted(true); setFormError(""); }, onError: error => setFormError(error.message || "We could not send the inquiry. Please try again.") });
  const toggleService = (item: InquiryType) => setRequestedServices(current => current.includes(item) ? current.filter(value => value !== item) : [...current, item]);
  const reset = () => { setStep(0); setRequestedServices([]); setPropertyType(""); setLocation(""); setProjectDetails(""); setInspirationUrl(""); setName(""); setEmail(""); setPhone(""); setBestContactTime(""); setFormError(""); setSubmitted(false); inquiry.reset(); };
  const dismiss = () => { reset(); onClose(); };
  useEffect(() => { if (!open) return; const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") dismiss(); }; window.addEventListener("keydown", closeOnEscape); return () => window.removeEventListener("keydown", closeOnEscape); }, [open]);
  if (!open) return null;
  const validateStep = (target = step) => { const valid = target === 0 ? requestedServices.length > 0 : target === 1 ? Boolean(propertyType) : target === 2 ? location.trim().length > 0 : target === 3 ? projectDetails.trim().length > 0 : target === 5 ? Boolean(name.trim() && /^\S+@\S+\.\S+$/.test(email.trim())) : true; if (!valid) { setFormError(target === 5 ? "Please provide a name and valid email address." : "Please complete this step before continuing."); } else { setFormError(""); } return valid; };
  const advance = () => { if (validateStep()) setStep(current => Math.min(5, current + 1)); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (!validateStep(5)) return; inquiry.mutate({ requestedServices, propertyType: propertyType as (typeof propertyTypes)[number], location: location.trim(), projectDetails: projectDetails.trim(), inspirationUrl: inspirationUrl.trim(), name: name.trim(), email: email.trim(), phone: phone.trim(), bestContactTime: bestContactTime.trim() }); };
  const inputClass = "w-full rounded-xl border border-[#1d2b20]/20 bg-white px-4 py-3 text-sm font-medium text-[#1d2b20] shadow-sm outline-none placeholder:text-[#52705b]/65 focus:border-[#35563d] focus:ring-2 focus:ring-[#b9d3b5]";
  const questionHeadingClass = "display text-4xl font-semibold leading-[0.95] text-[#1b2e20] md:text-5xl";

  return <div className="fixed inset-0 z-[70] grid place-items-center p-4" role="dialog" aria-modal="true" aria-labelledby="contact-dialog-title"><button className="absolute inset-0 bg-[#0b1710]/55 backdrop-blur-md" onClick={dismiss} aria-label="Close contact form" /><div className="relative max-h-[calc(100vh-2rem)] w-full max-w-4xl overflow-y-auto rounded-[1.5rem] border border-white/10 bg-[#f8f7f1] shadow-[0_30px_90px_rgba(3,12,7,0.45)]"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-[#1d2b20]/10 bg-[#f8f7f1]/96 px-6 py-4 backdrop-blur md:px-8"><div><p className="eyebrow text-[#52705b]">Project inquiry</p><p className="mt-1 text-sm font-semibold text-[#1d2b20]">Canyon Outdoor</p></div><button onClick={dismiss} className="grid h-10 w-10 place-items-center rounded-full bg-[#173221] text-white" aria-label="Close contact form"><X size={18} /></button></div>{submitted ? <div className="grid min-h-[520px] place-items-center p-8 text-center md:p-14"><div className="max-w-lg"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#173221] text-white"><Check size={25} /></div><h2 id="contact-dialog-title" className="display mt-7 text-5xl font-semibold leading-[0.92]">WE'VE GOT IT.</h2><p className="mx-auto mt-5 max-w-md text-base leading-7 text-[#1d2b20]/65">Thanks for reaching out to Canyon Outdoor. We will review your project information and get back to you.</p><button onClick={dismiss} className="mt-8 rounded-full bg-[#173221] px-5 py-3 text-sm font-semibold text-white">Close</button></div></div> : <form onSubmit={submit} className="grid lg:grid-cols-[0.3fr_0.7fr]"><aside className="bg-[#173221] p-7 text-white md:p-9"><p className="display text-4xl font-bold leading-none">0{step + 1}<span className="text-white/30">/06</span></p><p className="mt-7 max-w-xs text-sm leading-7 text-white/70">A few details now help us begin a more useful conversation about your outdoor space.</p><div className="mt-12 flex gap-2">{[0, 1, 2, 3, 4, 5].map(item => <button type="button" key={item} onClick={() => setStep(item)} className={`h-2.5 rounded-full transition-all ${step === item ? "w-8 bg-[#b9d3b5]" : "w-2.5 bg-white/25"}`} aria-label={`Go to form step ${item + 1}`} />)}</div></aside><div className="min-h-[470px] p-7 md:p-10 lg:p-12">
		    {step === 0 && <div><h2 id="contact-dialog-title" className={questionHeadingClass}>WHAT ARE YOU<br />IMAGINING?</h2><p className="mt-4 text-sm leading-6 text-[#1d2b20]/60">Choose anything that feels relevant right now.</p><div className="mt-8 grid gap-2 sm:grid-cols-2">{inquiryTypes.map(item => <button type="button" key={item} onClick={() => toggleService(item)} className={`flex items-center justify-between rounded-xl border p-4 text-left text-sm font-semibold transition-colors ${requestedServices.includes(item) ? "border-[#35563d] bg-[#e0e7d9] text-[#173221]" : "border-[#1d2b20]/15 bg-white text-[#1d2b20] hover:border-[#35563d]"}`}><span>{item}</span>{requestedServices.includes(item) && <Check size={17} className="text-[#35563d]" />}</button>)}</div></div>}
	    {step === 1 && <div><h2 id="contact-dialog-title" className={questionHeadingClass}>WHAT KIND OF<br />PROPERTY IS IT?</h2><div className="mt-8 grid gap-3 sm:grid-cols-3">{propertyTypes.map(item => <button type="button" key={item} onClick={() => setPropertyType(item)} className={`min-h-32 rounded-2xl border p-5 text-left text-lg font-semibold transition-colors ${propertyType === item ? "border-[#35563d] bg-[#e0e7d9] text-[#173221]" : "border-[#1d2b20]/15 bg-white text-[#1d2b20] hover:border-[#35563d]"}`}>{item}</button>)}</div></div>}
	    {step === 2 && <div><h2 id="contact-dialog-title" className={questionHeadingClass}>WHERE IS THE<br />PROJECT LOCATED?</h2><p className="mt-4 text-sm leading-6 text-[#1d2b20]/60">A city or general neighborhood is enough for a first look.</p><input value={location} onChange={event => setLocation(event.target.value)} maxLength={160} placeholder="e.g. Costa Mesa, CA" className={`${inputClass} mt-10 text-lg`} /></div>}
	    {step === 3 && <div><h2 id="contact-dialog-title" className={questionHeadingClass}>WHAT SHOULD<br />FEEL DIFFERENT?</h2><textarea value={projectDetails} onChange={event => setProjectDetails(event.target.value)} maxLength={2000} placeholder="Tell us about the site, what is not working now, and the experience you are hoping to create." className={`${inputClass} mt-8 min-h-52 resize-none p-5 leading-7`} /></div>}
	    {step === 4 && <div><h2 id="contact-dialog-title" className={questionHeadingClass}>SHOW US WHAT<br />INSPIRES YOU.</h2><div className="mt-8 rounded-2xl border border-[#1d2b20]/15 bg-[#e0e7d9]/55 p-6"><LinkIcon size={22} className="text-[#35563d]" /><label className="mt-5 grid gap-2 text-sm font-semibold text-[#1d2b20]">Reference image link (optional)<input value={inspirationUrl} onChange={event => setInspirationUrl(event.target.value)} type="url" maxLength={2048} placeholder="https://example.com/inspiration.jpg" className={inputClass} /></label><p className="mt-4 text-xs leading-5 text-[#1d2b20]/60">To protect the site, direct file uploads are not accepted. You can add a public link or describe your inspiration in the project details.</p></div></div>}
	    {step === 5 && <div><h2 id="contact-dialog-title" className={questionHeadingClass}>HOW CAN WE<br />REACH YOU?</h2><div className="mt-8 grid gap-4 sm:grid-cols-2"><input value={name} onChange={event => setName(event.target.value)} required maxLength={120} placeholder="Name" className={inputClass} /><input value={email} onChange={event => setEmail(event.target.value)} required type="email" maxLength={320} placeholder="Email address" className={inputClass} /><input value={phone} onChange={event => setPhone(event.target.value)} maxLength={32} placeholder="Phone (optional)" className={inputClass} /><input value={bestContactTime} onChange={event => setBestContactTime(event.target.value)} maxLength={120} placeholder="Best time to connect (optional)" className={inputClass} /></div><p className="mt-6 text-xs leading-5 text-[#1d2b20]/60">Canyon Outdoor provides landscape design, outdoor living concepts, hardscape concepts, and property visualization. We are not a licensed contractor or construction company.</p></div>}
    {formError && <p role="alert" className="mt-6 rounded-xl bg-[#f7e4de] px-4 py-3 text-sm font-semibold text-[#8a2c1f]">{formError}</p>}<div className="mt-12 flex items-center justify-between border-t border-[#1d2b20]/12 pt-5"><button type="button" onClick={() => { setFormError(""); setStep(current => Math.max(0, current - 1)); }} disabled={step === 0 || inquiry.isPending} className="flex items-center gap-1 text-sm font-semibold disabled:opacity-25"><ChevronLeft size={16} />Back</button>{step < 5 ? <button type="button" onClick={advance} className="flex items-center gap-2 rounded-full bg-[#173221] px-5 py-3 text-sm font-semibold text-white">Continue <ChevronRight size={16} /></button> : <button type="submit" disabled={inquiry.isPending} className="rounded-full bg-[#35563d] px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{inquiry.isPending ? "Sending…" : "Send inquiry"}</button>}</div></div></form>}</div></div>;
}
