/** Canyon Outdoor shared contact surface: a compact, consistent inquiry form that can live naturally at the end of every page. */
import { FormEvent, useState } from "react";
import { Check, Send } from "lucide-react";

export function QuickContactForm() {
  const [sent, setSent] = useState(false);
  const submit = (event: FormEvent) => { event.preventDefault(); setSent(true); };

  return <section className="bg-[#e0e7d9] py-20 text-[#1d2b20] md:py-28" aria-labelledby="contact-form-title"><div className="container"><div className="grid gap-10 lg:grid-cols-[0.85fr_1.15fr] lg:items-end"><div><p className="eyebrow text-[#52705b]">Start a conversation</p><h2 id="contact-form-title" className="display mt-4 max-w-xl text-5xl font-bold leading-[0.9] md:text-6xl">TELL US ABOUT<br />YOUR SPACE.</h2><p className="mt-5 max-w-md text-base leading-7 text-[#1d2b20]/67">Share the essentials and we will use them to begin a more useful conversation about your outdoor environment.</p></div>{sent ? <div className="rounded-[1.25rem] bg-[#173221] p-7 text-white md:p-9"><div className="grid h-12 w-12 place-items-center rounded-full bg-[#b9d3b5] text-[#173221]"><Check size={22} /></div><h3 className="display mt-6 text-3xl font-bold leading-[0.92]">THANK YOU.</h3><p className="mt-4 max-w-md text-sm leading-7 text-white/72">Your inquiry is noted. Canyon Outdoor will review the details and follow up soon.</p><button onClick={() => setSent(false)} className="mt-7 rounded-full border border-white/25 px-4 py-2.5 text-sm font-semibold text-white">Send another inquiry</button></div> : <form onSubmit={submit} className="rounded-[1.25rem] bg-[#f9f8f3] p-6 shadow-[0_18px_45px_rgba(35,52,38,0.1)] md:p-8"><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Name<input required name="name" placeholder="Your name" className="rounded-xl border border-[#1d2b20]/15 bg-white px-4 py-3 text-sm font-normal outline-none placeholder:text-[#1d2b20]/35 focus:border-[#35563d]" /></label><label className="grid gap-2 text-sm font-semibold">Email<input required name="email" type="email" placeholder="you@example.com" className="rounded-xl border border-[#1d2b20]/15 bg-white px-4 py-3 text-sm font-normal outline-none placeholder:text-[#1d2b20]/35 focus:border-[#35563d]" /></label></div><label className="mt-4 grid gap-2 text-sm font-semibold">What are you hoping to create?<textarea required name="message" rows={4} placeholder="Tell us about your property, how you want to use it, and what you would like to change." className="resize-none rounded-xl border border-[#1d2b20]/15 bg-white p-4 text-sm font-normal leading-6 outline-none placeholder:text-[#1d2b20]/35 focus:border-[#35563d]" /></label><button type="submit" className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#173221] px-5 py-3 text-sm font-semibold text-white transition-transform active:scale-95">Send inquiry <Send size={15} /></button></form>}</div></div></section>;
}
